name: Lunch CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  container-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: eclipse-temurin:21.0.2_13-jdk
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Clean with Gradle Wrapper
        run: ./gradlew clean

      - name: Unit Test with Gradle Wrapper
        run: ./gradlew test --tests "service.*"

      - name: Assemble with Gradle Wrapper
        run: ./gradlew assemble
