name: Lunch CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  jar-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: eclipse-temurin:21.0.2_13-jdk
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Clean with Gradle Wrapper
        run: ./gradlew clean

      - name: Unit Test with Gradle Wrapper
        run: ./gradlew test --tests "service.*"

      - name: Assemble with Gradle Wrapper
        run: ./gradlew assemble
      - uses: actions/upload-artifact@v4
        with: 
          name: upload-jar
          path: build/libs/team4-office-lunch-management-0.1-all.jar
  image-build:
    needs: jar-build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with: 
          name: upload-jar
          path: .
      - name: Build Docker image
        run: docker build -t sample .
        
      

        

