name: Lunch CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  container-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: eclipse-temurin:21.0.2_13-jdk
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
    # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Clean with Gradle Wrapper
        run: ./gradlew clean

      - name: Compile with Gradle Wrapper
        run: ./gradlew assemble

      - name: Unit Test with Gradle Wrapper
        run: ./gradlew test --tests "service.*"

      - name: Build with Gradle Wrapper
        run: ./gradlew build
